Description of NumIntegration
Home > DIDAN > NumIntegration.m
NumIntegration
PURPOSE
SYNOPSIS
function [tnew,Unew]=NumIntegration(coef,vtau,RHS,t,U,Uss,isolver,Tadd,delta,err,interp1_method,iresult,nfig,iclean,h,v,mark,inc,scheme,varname,logind)
DESCRIPTION
 Latest revision 05.11.2019
 Численное интегрирование модели по времени
 Внешние процедуры: Matrices, Ploter, Function
 Внутренние процедуры: Step, Res, Jacob
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 ВХОДНЫЕ ПАРАМЕТРЫ:
 coef,vtau - параметры модели
 t - сетка по времени
 U - решение в узлах сетки t
 Uss - стационарное состояние (при нелинейном интегрировании не используется)
 isolver=1 - нелинейное интегрирование: решается задача Коши для исходной
             системы в интервале времени от t(end) до t(end)+Tadd
             с начальными значениями взятыми из U;
 isolver=2,3 - линейное интегрирование: решается задача Коши для системы,
               линеаризованной относительно стационарного состояния Uss,
               в интервале времени от t(end) до t(end)+Tadd с начальными
               значениями взятыми из  U-Uss, к найденному решению
               добавляется Uss.
 Tadd -  время интегрирования
 delta - шаг сетки
 err - точность метода Ньютона (при линейном интегрировании не используется)
 interp1_method - метод интерполяции: 'linear', 'spline', 'pchip'
 iresult=1 - дополнить старое решение новым расчетом,
         2 - сохранить только новый расчет,
         3 - сохранить только "хвост" нового расчета, необходимый для
             продолжения интегрирования,
         4 - сохранить новый расчет и начальные данные для него.
 nfig - номер фигуры (если nfig<1, то картинка не рисуется).
 iclean=1 - чистить картинку.
 mark - тип линий на графиках
 inc - инкремент выдачи на экран
 scheme - схема интегрирования: 1 - неявный метод Эйлера,
                                2 - BDF2.
 ВЫХОДНЫЕ ПАРАМЕТРЫ:
 tnew - новая сетка по времени
 Unew - решение в узлах новой сетки
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
Matrices
Ploter
matlabFunction_new
rhsm RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
This function is called by:
PeriodicSolutions
SUBFUNCTIONS
function [U,l]=Step(Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,err,scheme)
function G=Res(U,Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme)
function dGdU=Jacob(U,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme)
SOURCE CODE
function [tnew,Unew]=NumIntegration(coef,vtau,RHS,t,U,Uss,isolver,...
                            Tadd,delta,err,interp1_method,iresult,...
                                               nfig,iclean,h,v,mark,inc,scheme,varname,logind)
%
% Latest revision 05.11.2019
%
% Численное интегрирование модели по времени
%
% Внешние процедуры: Matrices, Ploter, Function
%
% Внутренние процедуры: Step, Res, Jacob
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ВХОДНЫЕ ПАРАМЕТРЫ:
%
% coef,vtau - параметры модели
%
% t - сетка по времени
% U - решение в узлах сетки t
% Uss - стационарное состояние (при нелинейном интегрировании не используется)
%
% isolver=1 - нелинейное интегрирование: решается задача Коши для исходной
%             системы в интервале времени от t(end) до t(end)+Tadd
%             с начальными значениями взятыми из U;
%
% isolver=2,3 - линейное интегрирование: решается задача Коши для системы,
%               линеаризованной относительно стационарного состояния Uss,
%               в интервале времени от t(end) до t(end)+Tadd с начальными
%               значениями взятыми из  U-Uss, к найденному решению
%               добавляется Uss.
%
% Tadd -  время интегрирования
% delta - шаг сетки
% err - точность метода Ньютона (при линейном интегрировании не используется)
%
%
% interp1_method - метод интерполяции: 'linear', 'spline', 'pchip'
%
% iresult=1 - дополнить старое решение новым расчетом,
%         2 - сохранить только новый расчет,
%         3 - сохранить только "хвост" нового расчета, необходимый для
%             продолжения интегрирования,
%         4 - сохранить новый расчет и начальные данные для него.
%
% nfig - номер фигуры (если nfig<1, то картинка не рисуется).
% iclean=1 - чистить картинку.
% mark - тип линий на графиках
% inc - инкремент выдачи на экран
%
% scheme - схема интегрирования: 1 - неявный метод Эйлера,
%                                2 - BDF2.
%
% ВЫХОДНЫЕ ПАРАМЕТРЫ:
% tnew - новая сетка по времени
% Unew - решение в узлах новой сетки
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[filepath,~,~] = fileparts(mfilename('fullpath'));
addpath(genpath(filepath));
% Формирование функции matlab, вычисляющей правую часть системы
[Var,F]=RHS(coef);
matlabFunction_new(F,'rhsm.m',Var);
%
% Формирование функции matlab, вычисляющей матрицу Якоби
dGdU=jacobian(F,Var{1,1});
matlabFunction_new(dGdU,'jac.m',Var);
%
% Сетка по времени для новых расчетов:
vtau = sort(vtau);
vm=ceil(vtau/delta);
vm1=zeros(10,1); %%%%TODO:WHY 10?
vm1(1:size(vm,1))=vm;
mp=vm(end);
K=ceil(Tadd/delta);
if(K==0)
   disp('Время интегрирования меньше одного шага')
   STOP
end
tadd=t(end)+((1-mp):1:K)*delta;
% tadd(1)=t(end)-tau_A+delta=t(end)-(mp-1)*delta
% tadd(1+mp-m)=t(end)-tau+delta=t(end)-(m-1)*delta
% tadd(mp)=t(end)
% tadd(mp+K)=t(end)+T=t(end)+K*delta
%
% Формирование матрицы начальных значений:
Uadd=zeros(size(Var{1,1},1),mp+K);
k=sum(t-t(end)<=-vtau(end));
if(k<1)
   disp('t(1)>t(end)-tau_A')
   STOP
end
%Встроенная функция для интерполирования
Uadd(:,1:mp)=interp1(t(k:end),U(:,k:end)',tadd(1:mp),interp1_method)';
%
if(isolver==1)
% Нелинейное интегрирование по времени:
   nns=0;
   for k=mp+1:mp+K
      [Uadd(:,k),nnsk]=Step(Uadd(:,k-1),Uadd(:,k-2),Uadd(:,k-vm1(1)),...
                                    Uadd(:,k-vm1(2)),Uadd(:,k-vm1(3)),...
                                    Uadd(:,k-vm1(4)),Uadd(:,k-vm1(5)),...
                                    Uadd(:,k-vm1(6)),Uadd(:,k-vm1(7)),...
                                    Uadd(:,k-vm1(8)),Uadd(:,k-vm1(9)),...
                                    Uadd(:,k-vm1(10)),delta,err,scheme);
      nns=nns+nnsk;
      %nnsk-кол-во итераций метода Ньютона за один шаг по сетке времени
      if (mod(k-mp,inc)==0) % информация о работе метода
         fprintf(1,'t=%g, nns=%g\n',t(end)+(k-mp)*delta,nns);
         nns=0;
      end
      %if (nnsk==10)
       %   fprintf('t=%g\n',t(end)+(k-mp)*delta);
        %  pause
          %fprintf(Norm);
          %fprintf('t=%g, iter=%g, n_be=%g, n_af=%g ratio=%g\n',t(end)+(k-mp)*delta,nnsk,k1,k2,k1/k2);
          %pause
      %end
   end
elseif(isolver==2)
% Линейное интегрирование по времени:
   [~,CM]=Matrices(Uss,coef,delta,vtau,scheme);
   Uadd(:,1:mp)=Uadd(:,1:mp)-Uss*ones(1,mp);
   for k=mp+1:mp+K
       Uadd(:,k)=CM{1,1}*Uadd(:,k-1)+CM{1,2}*Uadd(:,k-2);
       for j=3:size(CM,2)
           Uadd(:,k)=Uadd(:,k)+CM{1,j}*Uadd(:,k-vm(j-2));
       end
      if (mod(k-mp,inc)==0)
         fprintf(1,'t=%g\n',(k-mp)*delta);
      end
   end
   Uadd=Uadd+Uss*ones(1,size(Uadd,2));
elseif(isolver==3)
% Линейное интегрирование по времени:
   [~,~,M]=Matrices(Uss,coef,delta,m,mp,scheme);
   Uadd(:,1:mp)=Uadd(:,1:mp)-Uss*ones(1,mp);
   X=Uadd(:,mp:-1:1);
   X=sparse(X(:));
   for k=mp+1:mp+K
      X=M*X;
      Uadd(:,k)=full(X(1:size(Uss,1)));
      if (mod(k-mp,inc)==0)
         fprintf(1,'t=%g\n',(k-mp)*delta);
      end
   end
   Uadd=Uadd+Uss*ones(1,size(Uadd,2));
end
% Отрисовка нового расчета и его начальных данных:
if (nfig>0)
   figure(nfig)
 Ploter(tadd,Uadd,mark,iclean,h,v,varname,logind)
end
%
if(iresult==1)
% дополнить старое решение новыми расчетами:
   tnew=[t,tadd(mp+1:mp+K)];
   Unew=[U,Uadd(:,mp+1:mp+K)];
elseif(iresult==2)
% сохранить только новый расчет:
   tnew=tadd(mp+1:mp+K);
   Unew=Uadd(:,mp+1:mp+K);
elseif(iresult==3)
% сохранить только "хвост" нового расчета, необходимый для продолжения интегрирования:
   tnew=tadd(K:mp+K);
   Unew=Uadd(:,K:mp+K);
elseif(iresult==4)
% сохранить новый расчет и начальные данные для него:
   tnew=tadd;
   Unew=Uadd;
end
clear t U tadd Uadd
delete jac.m
delete rhsm.m
function [U,l]=Step(Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,err,scheme)
%
% Latest revision 03.01.2017
%
% Шаг решения задачи Коши.
%
% Udelta,Udelta2,Vtau,Eptau,Vtaua - заданные  значения
% U - значение в следующем узле сетки
% coef - коэффициенты модели
% delta - шаг сетки
% err - точность решения нелинейного уравнения, к которому сводиться
%       реализация шага метода
% scheme=1 - неявный метод Эйлера
%        2 - BDF2
%
U=Udelta;
G=Res(U,Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme);
normG=norm(G,2);
err=err*norm(U,2);
l=0;
while(normG>err && l<15)%ограничить число шагов
   U=U-Jacob(U,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme)\G;
   U(U<0)=0;
   G=Res(U,Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme);
   normG=norm(G,2);
   l=l+1;
   %if l>1000
   %    disp(norm(G,2));
    %   if l==1120
    %       stop
    %   end
   %end
end
function G=Res(U,Udelta,Udelta2,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme)
%
% Latest revision 03.01.2017
%
if(scheme==1)
   G=(U-Udelta)/delta;
elseif(scheme==2)
   G=(1.5*(U-Udelta)+0.5*(Udelta2-Udelta))/delta;
end
g=rhsm(U,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10);
G=G-g';
function dGdU=Jacob(U,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10,delta,scheme)
%
% Latest revision 12.10.2019
%
%
if(scheme==1)
   dGdU=(1.0/delta)*eye(size(U,1));
elseif(scheme==2)
   dGdU=(1.5/delta)*eye(size(U,1));
end
dGdU=dGdU-jac(U,U1,U2,U3,U4,U5,U6,U7,U8,U9,U10);