Description of rhsm
Home > DIDAN > rhsm.m
rhsm
PURPOSE
RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
SYNOPSIS
function F=rhsm(in1,in2,in3,in4,in5,in6,varargin)
DESCRIPTION
RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Residual
NumIntegration
StStatesAnalysis StStatesAnalysis Analyzes steady states of a viral infection model with delayed immune response
SOURCE CODE
function F=rhsm(in1,in2,in3,in4,in5,in6,varargin)
 %RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
B=in1(8,:);
B_tau_B=in5(8,:);
B_tau_P=in6(8,:);
C_V=in1(2,:);
E_=in1(6,:);
E_tau_E=in4(6,:);
F_=in1(10,:);
H_B=in1(7,:);
H_B_tau_B=in5(7,:);
H_B_tau_P=in6(7,:);
H_B_tau_H_B=in3(7,:);
H_E=in1(5,:);
H_E_tau_E=in4(5,:);
H_E_tau_H_E=in2(5,:);
M_V=in1(4,:);
M_V_tau_B=in5(4,:);
M_V_tau_E=in4(4,:);
M_V_tau_P=in6(4,:);
M_V_tau_H_B=in3(4,:);
M_V_tau_H_E=in2(4,:);
P=in1(9,:);
V_f=in1(1,:);
m=in1(3,:);
t2=C_V.*(1.3e+1./2.5e+2);
t3=m./1.88125e+7;
t4=C_V+m-3.01e+8;
t5=m./1.505e+8;
t8=C_V.*E_.*1.096345514950166e-6;
t6=t3-1.6e+1;
t7=t5-2.0;
mt1=[C_V.*8.3e+1-V_f.*(2.0./5.0)+V_f.*t4.*4.152823920265781e-14+C_V.*E_.*5.481727574750831e-6-F_.*V_f.*4.983388704318937e-10];
mt2=[-t2-t8-V_f.*t4.*3.820598006644519e-12,m.*(-3.0./2.0e+1)+t2+t8,M_V.*(-6.0./5.0)+V_f.*9.4e-6];
mt3=[-H_E-H_E.*M_V.*4.485049833887043e-5-E_.*H_E.*M_V.*1.462456264279644e-14-H_E_tau_H_E.*M_V_tau_H_E.*t7.*4.485049833887043e-5+6.02e+2];
mt4=[E_.*(-2.0./5.0)-C_V.*E_.*2.657807308970099e-7-E_.*H_E.*M_V.*1.462456264279644e-8-E_tau_E.*H_E_tau_E.*M_V_tau_E.*t6.*1.462456264279644e-8+2.408e+2];
mt5=[-H_B-H_B.*M_V.*4.485049833887043e-5-B.*H_B.*M_V.*2.207481153629651e-13-H_B_tau_H_B.*M_V_tau_H_B.*t7.*4.485049833887043e-5+3.01e+2./5.0];
mt6=[B.*(-1.0./1.0e+1)-B.*H_B.*M_V.*2.207481153629651e-9-B_tau_B.*H_B_tau_B.*M_V_tau_B.*t6.*2.207481153629651e-9+3.01e+2./5.0];
mt7=[P.*(-2.0./5.0)-B_tau_P.*H_B_tau_P.*M_V_tau_P.*(m.*4.675313074547849e-20-1.407269235438903e-11)+1.03544e-1,F_.*(-4.3e+1./1.0e+3)+P.*1.7e+8-F_.*V_f.*1.428571428571429e-9];
F=reshape([mt1,mt2,mt3,mt4,mt5,mt6,mt7],1,10);