Description of StStatesAnalysis
Home > DIDAN > StStatesAnalysis.m
StStatesAnalysis
PURPOSE
StStatesAnalysis Analyzes steady states of a viral infection model with delayed immune response
SYNOPSIS
function [SS,Resid,EiVals,EiVects]=StStatesAnalysis(coef, delays, RHS, SSFinder, resFile)
DESCRIPTION
 StStatesAnalysis  Analyzes steady states of a viral infection model with delayed immune response
 [SS,RESID,EIVALS,EIVECTS] = StStatesAnalysis(COEF, DELAYS, RHS, SSFINDER,
 RESFILE) computes all steady states of a viral infection model formulated
 as a system of nonlinear delay differential equations and analyzes their
 stability.
 Steady states of such differential system for fixed values of parameters
 are nonnegative solutions to the system F(X) = 0.
 EXTERNAL FUNCTIONS: EigProbSol
 INTERNAL FUNCTIONS: -
 INPUTS:
   COEF:       struct with K fields where K is the total number of the
               given model parameters. The field names are the model
               parameter names, and the values in the fields are the
               corresponding model parameter values for which the steady
               states are to be computed and analyzed.
               For example, for the model with three parameters a = 1, b =
               2, c = 3, COEF is the struct with three fields:
                      a: 1
                      b: 2
                      c: 3
               Also, see examples of creating such struct in: HBV_Coef,
               LCMV_Coef.
   DELAYS:    Mx1 column vector of delays where M is the total number of
              the model delays.
              NOTE: The delays in the vector must be sorted in increasing
              order.
              For example, for the model with four delays: t1 = 1, t2 = 2,
              t3 = 4, t4 = 2, the vector DELAYS is [1; 2; 2; 4].
              Also, see examples of creating such coulumn vector in:
              HBV_Coef, LCMV_Coef.
   RHS:       callback funcion [U,F]=RHS(COEF) where:
                  - COEF is the same struct as the first argument of
                    StStatesAnalysis (see COEF's  description above).
                  - U is the 1x(M+1) cell array where M is the total
                    number of the model delays.
                    For i = 1:M+1, U{1,i} is the Nx1 column vector of
                    symbolic variables where N is the total numer of the
                    model variables.
                    U{1,1} contains the designations of all the model
                    variables in the same order that the model right-hand
                    sides describing variable temporal variations are
                    given in F (see F's description below).
                    For i = 2:M+1, U{1,i} contains the designations of all
                    the model variables for the (i - 1)-th delay from the
                    vector DELAYS which is the second argument of
                    StStatesAnalysis (See DELAYS' description above).
                    For example, the model has three variables A, B, C and
                    two delays - t1 and t2, t2 < t1. In this case, the
                    vector DELAYS is [t2; t1], since t2 < t1 and the
                    delays must be sorted in increasing order. So, U may be
                    created as follows:
                    ==================CODE-EXAMPLE=========================
                    |1    syms A B C A_t1, B_t1 C_t1, A_t2, B_t2 C_t2
                    |2    U{1,1} = [A;    B;    C   ];
                    |3    U{1,2} = [A_t2; B_t2; C_t2];
                    |4    U{1,3} = [A_t1; B_t1; C_t1];
                    =======================================================
                    NOTE 1: The order of the variable designations is the
                    same for any cell in the cell array U (see the code
                    example above).
                    NOTE 2: For i = 2:M+1, U{1,i} must contain the
                    variable designations for the i-th delay in the DELAYS
                    array (see the code example above).
                  - F is the 1xN row vector where N is the total number
                    of the model variables. The vector elements are the
                    right-hand sides of the model's delay differential
                    equations given as symbolic functions that use the
                    parameter values and the symbolic variables
                    contained in the struct COEF and in the cell array U
                    respectively.
                    NOTE: The right-hand sides must go in the same order
                    that the variables whose temporal variations they
                    describe are given in any cell of the cell array
                    U.(see U's description above). Thus, for U shown in
                    the code example above, F(1) must describe A's
                    variation, F(2) - B's variation, and F(3) - C's
                    variationa.
                    Also, see examples of creating F in: HBV_RHS,
                    LCMV_Coef.
  SSFINDER:   autogenerated callback function IG = SSFINDER(COEF) where:
                  - COEF is the same struct as the first argument of
                    StStatesAnalysis (see COEF's  description
                    above).
                  - IG is the NxS matrix where N is the total number
                    of the model variables, and S is the number of the
                    solutions to the system F(X) = 0 found by SSFINDER,
                    where X is the vector of the model variables which
                    doesn't depend on time and F(X) is the initial system
                    right-hand side. For each i = 1:S, the column vector
                    IG(:, i) is one of the found solutions. For the
                    correctly generated SSFINDER, the index number of a
                    certain variable in each found solution corresponds to
                    the index number of the right-hand side describing
                    this variabe temporal variation in the row vector with
                    right-hand sides returned by RHS (see RHS's
                    description above).
  RESFILE:    output file to save the matrices: SS, EIVALS, and EIVECTS
              that StStatesAnalysis returns (See description below)
 OUTPUTS:
  SS:         NxS matrix where N is the total number
              of the model variables, and S is the number of the found
              steady states. The steady states are found as For each i =
              1:S, SS(i, :) is one of the found steady states.
  RESID:      scalar value. 2-matrix-norm residual for the SS.
  EIVALS:
  EIVECTS:
 AUTHORS: M. Yu. Khristichenko, Yu. M. Nechepurenko, E. V. Sklyarova
 VERSION: 21.09.2021
CROSS-REFERENCE INFORMATION
This function calls:
EigProbSol
Residual
matlabFunction_new
rhsm RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
This function is called by:
SOURCE CODE
function [SS,Resid,EiVals,EiVects]=StStatesAnalysis(coef, delays, RHS, SSFinder, resFile)
% StStatesAnalysis  Analyzes steady states of a viral infection model with delayed immune response
%
% [SS,RESID,EIVALS,EIVECTS] = StStatesAnalysis(COEF, DELAYS, RHS, SSFINDER,
% RESFILE) computes all steady states of a viral infection model formulated
% as a system of nonlinear delay differential equations and analyzes their
% stability.
%
% Steady states of such differential system for fixed values of parameters
% are nonnegative solutions to the system F(X) = 0.
%
%
% EXTERNAL FUNCTIONS: EigProbSol
%
% INTERNAL FUNCTIONS: -
%
% INPUTS:
%   COEF:       struct with K fields where K is the total number of the
%               given model parameters. The field names are the model
%               parameter names, and the values in the fields are the
%               corresponding model parameter values for which the steady
%               states are to be computed and analyzed.
%               For example, for the model with three parameters a = 1, b =
%               2, c = 3, COEF is the struct with three fields:
%                      a: 1
%                      b: 2
%                      c: 3
%               Also, see examples of creating such struct in: HBV_Coef,
%               LCMV_Coef.
%
%
%   DELAYS:    Mx1 column vector of delays where M is the total number of
%              the model delays.
%              NOTE: The delays in the vector must be sorted in increasing
%              order.
%              For example, for the model with four delays: t1 = 1, t2 = 2,
%              t3 = 4, t4 = 2, the vector DELAYS is [1; 2; 2; 4].
%
%              Also, see examples of creating such coulumn vector in:
%              HBV_Coef, LCMV_Coef.
%
%
%   RHS:       callback funcion [U,F]=RHS(COEF) where:
%                  - COEF is the same struct as the first argument of
%                    StStatesAnalysis (see COEF's  description above).
%
%                  - U is the 1x(M+1) cell array where M is the total
%                    number of the model delays.
%                    For i = 1:M+1, U{1,i} is the Nx1 column vector of
%                    symbolic variables where N is the total numer of the
%                    model variables.
%                    U{1,1} contains the designations of all the model
%                    variables in the same order that the model right-hand
%                    sides describing variable temporal variations are
%                    given in F (see F's description below).
%                    For i = 2:M+1, U{1,i} contains the designations of all
%                    the model variables for the (i - 1)-th delay from the
%                    vector DELAYS which is the second argument of
%                    StStatesAnalysis (See DELAYS' description above).
%
%                    For example, the model has three variables A, B, C and
%                    two delays - t1 and t2, t2 < t1. In this case, the
%                    vector DELAYS is [t2; t1], since t2 < t1 and the
%                    delays must be sorted in increasing order. So, U may be
%                    created as follows:
%                    ==================CODE-EXAMPLE=========================
%                    |1    syms A B C A_t1, B_t1 C_t1, A_t2, B_t2 C_t2
%                    |2    U{1,1} = [A;    B;    C   ];
%                    |3    U{1,2} = [A_t2; B_t2; C_t2];
%                    |4    U{1,3} = [A_t1; B_t1; C_t1];
%                    =======================================================
%                    NOTE 1: The order of the variable designations is the
%                    same for any cell in the cell array U (see the code
%                    example above).
%                    NOTE 2: For i = 2:M+1, U{1,i} must contain the
%                    variable designations for the i-th delay in the DELAYS
%                    array (see the code example above).
%
%                  - F is the 1xN row vector where N is the total number
%                    of the model variables. The vector elements are the
%                    right-hand sides of the model's delay differential
%                    equations given as symbolic functions that use the
%                    parameter values and the symbolic variables
%                    contained in the struct COEF and in the cell array U
%                    respectively.
%                    NOTE: The right-hand sides must go in the same order
%                    that the variables whose temporal variations they
%                    describe are given in any cell of the cell array
%                    U.(see U's description above). Thus, for U shown in
%                    the code example above, F(1) must describe A's
%                    variation, F(2) - B's variation, and F(3) - C's
%                    variationa.
%                    Also, see examples of creating F in: HBV_RHS,
%                    LCMV_Coef.
%
%
%  SSFINDER:   autogenerated callback function IG = SSFINDER(COEF) where:
%                  - COEF is the same struct as the first argument of
%                    StStatesAnalysis (see COEF's  description
%                    above).
%                  - IG is the NxS matrix where N is the total number
%                    of the model variables, and S is the number of the
%                    solutions to the system F(X) = 0 found by SSFINDER,
%                    where X is the vector of the model variables which
%                    doesn't depend on time and F(X) is the initial system
%                    right-hand side. For each i = 1:S, the column vector
%                    IG(:, i) is one of the found solutions. For the
%                    correctly generated SSFINDER, the index number of a
%                    certain variable in each found solution corresponds to
%                    the index number of the right-hand side describing
%                    this variabe temporal variation in the row vector with
%                    right-hand sides returned by RHS (see RHS's
%                    description above).
%
%
%  RESFILE:    output file to save the matrices: SS, EIVALS, and EIVECTS
%              that StStatesAnalysis returns (See description below)
%
% OUTPUTS:
%  SS:         NxS matrix where N is the total number
%              of the model variables, and S is the number of the found
%              steady states. The steady states are found as For each i =
%              1:S, SS(i, :) is one of the found steady states.
%
%  RESID:      scalar value. 2-matrix-norm residual for the SS.
%
%  EIVALS:
%
%  EIVECTS:
%
%
% AUTHORS: M. Yu. Khristichenko, Yu. M. Nechepurenko, E. V. Sklyarova
% VERSION: 21.09.2021
%
[filepath,~,~] = fileparts(mfilename('fullpath'));
addpath(genpath(filepath));
format long
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% УСТАНОВКА ПАРАМЕТРОВ:
%
tol=1e-6; % необходимая точность вычисления стационарного состояния
%
Esolver=2;  % Решатель частичных проблем:
            % 1 - метод сингулярной функции
            % 2 - метод частичных линейных проблем
            deflation=0; % режим дефляции (-1,0,1,2 либо 3)
%
addinf=0; % информация о потери ведущего собственного значения (0/1)
          %+ пошаговой информации о работе решателей частичных проблем (2)
%
p=10; % требуемое число собственных значений
ind=0; % нужно ли отрисовывать собственные значения на комплексной плоскости (0/1)
%сортируем по возрастанию
delays=sort(delays);
g=pwd;
mapa=which('math.exe');
mapa=mapa(1:end-8);
mapa = 'C:\Program Files\Wolfram Research\Mathematica\12.0'; %%%%TODO
cd(mapa);
addpath(g);
SS=SSFinder(coef);
cd(g);
SS=SS';
U0= [0; 0; 0; 0; coef.H_E_0; coef.E_0; coef.H_B_0; coef.B_0; coef.P_0; coef.rho_F*coef.P_0/coef.alpha_F]; %% TODO depends on the model
SS=[SS,U0];
Resid=zeros(1,size(SS,2));
for i=1:size(SS,2)
   if Residual(SS(:,i),coef, RHS)>tol
        l=0;
        [Var,F]=RHS(coef);
        matlabFunction_new(F,'rhsm.m',Var);
        Y=rhsm(SS(:,i),SS(:,i),SS(:,i),SS(:,i),SS(:,i),SS(:,i))';
        normY=norm(Y,2);
        for j=2:size(Var,2)
            for k=1:size(Var{1,1},1)
                F=subs(F,Var{1,j}(k),Var{1,1}(k));
            end
        end
        Jacob=jacobian(F,Var{1,1});
        while(normY>tol)
            jacob1=subs(Jacob,Var{1,1},SS(:,i));
            jacob1=double(jacob1);
            SS(:,i)=SS(:,i)-jacob1\Y;
            l=l+1;
            Y=rhsm(SS(:,i),SS(:,i),SS(:,i),SS(:,i),SS(:,i),SS(:,i))';
            normY=norm(Y,2);
        end
   end
   Resid(i)=Residual(SS(:,i),coef, RHS);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% II. АНАЛИЗ УСТОЙЧИВОСТИ. ВЫЧИСЛЕНИЕ СОБСТВЕННЫХ ЗНАЧЕНИЙ:
%
EiVals=[];
EiVects=[];
for k=1:size(SS,2)
    fprintf(1,'Для %d-го стационарного состояния: \n',k);
    Ui=SS(:,k);
    disp('Стационарное состояние:');
    disp(Ui);
    disp('Невязка:');
    disp(Residual(Ui,coef, RHS));
    addinf2=max(addinf-1,0);
    tic
    [Ei,Xi]=EigProbSol(RHS,Ui,coef,delays,p,Esolver,deflation,addinf2,ind,k);
    fprintf(1,'%d ведущих собственных значений: \n',p);
    disp(Ei);
    toc
    disp(' ');
    EiVals=[EiVals,Ei];
    EiVects=[EiVects,Xi];
end
save(resFile,'EiVals','EiVects','SS');