Description of matlabFunction_new
Home > DIDAN > Functions > matlabFunction_new.m
matlabFunction_new
PURPOSE
SYNOPSIS
function matlabFunction_new(F,filename,vars)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Residual
NumIntegration
PSolStabilityAnalysis
StStatesAnalysis StStatesAnalysis Analyzes steady states of a viral infection model with delayed immune response
SOURCE CODE
function matlabFunction_new(F,filename,vars)
matlabFunction(F,'File',filename,'Vars',vars);
fid=fopen(filename,'r');
C=fscanf(fid,'%s');
i=1;
while (C(i)~=')')
    i=i+1;
    j=i;
end
for k=1:size(C,2)
    if C(k)=='%'
        q=k;
    end
end
D=[C(1:8),' ',C(9:j-1),',varargin',C(j:end)];
fid_new=fopen(filename,'w');
fprintf(fid_new,'%s\n %s\n',D(1:j+10), D(j+11:29+q));
p=29+q;
for i=30+q:size(D,2)
    if D(i)==';'
        fprintf(fid_new,'%s\n', D(p+1:i));
        p=i;
    end
end
fclose(fid);
fclose(fid_new);