Description of Residual
Home > DIDAN > Functions > Residual.m
Residual
PURPOSE
SYNOPSIS
function [res]=Residual(S,coef,RHS)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
matlabFunction_new
rhsm RHSM%F=RHSM(IN1,IN2,IN3,IN4,IN5,IN6)%ThisfunctionwasgeneratedbytheSymbolicMathToolboxversion8.7.%20-Sep-202123:32:20
This function is called by:
StStatesAnalysis StStatesAnalysis Analyzes steady states of a viral infection model with delayed immune response
SOURCE CODE
function [res]=Residual(S,coef,RHS)
[Var,F]=RHS(coef);
matlabFunction_new(F,'rhsm.m',Var);
% format short E
a=rhsm(S,S,S,S,S,S);
res=norm(a,2);
%subs(F,{Var{1,1},Var{1,2},Var{1,3},Var{1,4},Var{1,5},Var{1,6}},{Uss,Uss,Uss,Uss,Uss,Uss});
%subs(F,Var{1,1},Uss)