Description of Matrices
Home > DIDAN > Functions > Matrices.m
Matrices
PURPOSE
SYNOPSIS
function [L,CM,M]=Matrices(RHS,Uss,coef,delta,vtau,scheme)
DESCRIPTION
 Latest revision 05.11.2019
 Вычисление матриц линеаризованной относительно стационарного состояния модели
 Внешние процедуры: RHS
 Внутренние процедуры: нет
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 ВХОДНЫЕ ПАРАМЕТРЫ:
 Uss - стационарное состояние,
 coef,vtau - параметры модели,
 delta - выбранный шаг сетки,
 scheme -схема интегрирования ( 1 - неявный метод Эйлера, 2 - BDF2)
 ВЫХОДНЫЕ ПАРАМЕТРЫ:
 L - матрицы линеаризованной модели
 CM - матрицы, использующиеся в разностной схеме
 M - большая матрица, использующаяся при поиске собственных значений.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EigProbSol
NumIntegration
OPT_DIST
SOURCE CODE
function [L,CM,M]=Matrices(RHS,Uss,coef,delta,vtau,scheme)
%
% Latest revision 05.11.2019
%
% Вычисление матриц линеаризованной относительно стационарного состояния модели
%
% Внешние процедуры: RHS
%
% Внутренние процедуры: нет
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ВХОДНЫЕ ПАРАМЕТРЫ:
% Uss - стационарное состояние,
% coef,vtau - параметры модели,
% delta - выбранный шаг сетки,
%
% scheme -схема интегрирования (1 - неявный метод Эйлера, 2 - BDF2)
%
% ВЫХОДНЫЕ ПАРАМЕТРЫ:
% L - матрицы линеаризованной модели
% CM - матрицы, использующиеся в разностной схеме
% M - большая матрица, использующаяся при поиске собственных значений.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
vtau = sort(vtau);
vm=ceil(vtau/delta);
mp=vm(end);
%
L=cell(1,(size(vtau,1)+1));
CM=cell(1,(size(vtau,1)+2));
[U,Func]=RHS(coef);
for i=1:size(U,2)
    %Встроенная функция
    L{1,i}=jacobian(Func,U{1,i});
    for j=2:size(U,2)
        %количество переменных
        for k=1:size(U{1,1},1)
            L{1,i}=subs(L{1,i},U{1,j}(k),U{1,1}(k));
        end
    end
        L{1,i}=subs(L{1,i},U{1,1},Uss);
   L{1,i}=double(L{1,i});
end
I=eye(size(Func,2));
if(scheme==1)
   C=(I-delta*L{1,1})\I;
   C1=C;
   C2=zeros(size(Func,2),size(Func,2));
elseif(scheme==2)
   C=(1.5*I-delta*L{1,1})\I;
   C1=2*C;
   C2=-0.5*C;
end
CM{1,1}=C1;
CM{1,2}=C2;
nov=size(U{1,1},1);
M=sparse(nov+1:1:nov*mp,1:1:nov*mp-nov,ones(nov*mp-nov,1),nov*mp,nov*mp,nov*mp-nov);
M(1:nov,1:nov)=sparse(C1);
M(1:nov,nov+1:2*nov)=sparse(C2);
for i=2:size(U,2)
    Ci=C*(delta*L{1,i});
    mi=vm(i-1);
    M(1:nov,nov*mi-nov+1:nov*mi)=M(1:nov,nov*mi-nov+1:nov*mi)+sparse(Ci);
    CM{1,i+1}=Ci;
end