Description of Ploter
Home > DIDAN > Functions > Ploter.m
Ploter
PURPOSE
SYNOPSIS
function Ploter(t,U,mark,iclean,h,v,varname,logind)
DESCRIPTION
 Latest revision 05.11.2019
 Отрисовка решения модели
 Внешние процедуры: нет
 Внутренние процедуры: нет
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 ВХОДНЫЕ ПАРАМЕТРЫ:
 t - сетка по времени
 U - решение в узлах сетки по времени
 mark - цвет линии отрисовываемых решений
 iclean - чистка графиков
 v,h - количество подрисунков по вертикали и горизонтали
 varname - структура, содержащая назавнич переменных
 logind - выбор между лоагрифмическим масштабом (1) и обычным (0)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
symlog2 SYMLOG bi-symmetric logarithmic axes scaling
This function is called by:
NumIntegration
OPT_DIST
PeriodicSolutions
SOURCE CODE
function Ploter(t,U,mark,iclean,h,v,varname,logind)
%
% Latest revision 05.11.2019
%
% Отрисовка решения модели
%
% Внешние процедуры: нет
%
% Внутренние процедуры: нет
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ВХОДНЫЕ ПАРАМЕТРЫ:
%
% t - сетка по времени
% U - решение в узлах сетки по времени
%
% mark - цвет линии отрисовываемых решений
% iclean - чистка графиков
% v,h - количество подрисунков по вертикали и горизонтали
%
% varname - структура, содержащая назавнич переменных
%
% logind - выбор между лоагрифмическим масштабом (1) и обычным (0)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
for i=1:size(U,1)
subplot(v,h,i)
   if(iclean)
       hold off
   end
   if (logind)
       semilogy(t,U(i,:),mark);
       symlog2('y');
   else
       plot(t,U(i,:),mark)
   end
   xlabel('$t$','Interpreter','latex');
   title(varname{1,i},'Interpreter','latex');
   hold on
end