Description of Tracing
Home > DIDAN > Functions > Tracing.m
Tracing
PURPOSE
SYNOPSIS
function SS=Tracing(Y,par,lbfname,ubfname, coef, tol, t)
DESCRIPTION
 Latest revision 28.04.2019
 Вычисление зависимости функии x(p) заданной неявно уравнением Y(p,x)=0
 Входные данные:    Y - функция Y(p,x), заданная символьно,
                    par - сетка по параметру p,
                    lbfname - название функции, отвечающей нижней границе области,
                    ubfname - название функции, отвечающей верхней границе области,
                    coef - коэффициенты системы
                    tol - точность fzero
                    t - если между точками расстрояние меньше t, то точки
                    совпадают
 Выходные данные: SS - структура, содержащая зависимость x(p)
 Внешние процедуры: Findingzeros, Newton,sorting
 Внутренние процедуры: Integr, ode45terminator,
 find_points_without_pair, termintor
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CROSS-REFERENCE INFORMATION
This function calls:
Findingzeros
Newton % Newton's method for solving a system of nonlinear equations
sorting
This function is called by:
SUBFUNCTIONS
function [ss,break_point]=Integr(xbeg,par,dYdx,F,Ysyms,lbfname,ubfname,opt,coef)
function [t, y] = Integr_vertical(t0, y0, F_vertical, opt_vertical, dir, dt, lbfname, ubfname, coef)
function points_without_pair = find_points_without_pair(break_points, tol)
function [value,isterminal,direction] = ode45terminator(X,p,dfdx)
function [value,isterminal,direction] = terminator(X,p,dfdx,lbfname,ubfname,coef)
SOURCE CODE
function SS=Tracing(Y,par,lbfname,ubfname, coef, tol, t)
%
% Latest revision 28.04.2019
%
% Вычисление зависимости функии x(p) заданной неявно уравнением Y(p,x)=0
%
% Входные данные:    Y - функция Y(p,x), заданная символьно,
%                    par - сетка по параметру p,
%                    lbfname - название функции, отвечающей нижней границе области,
%                    ubfname - название функции, отвечающей верхней границе области,
%                    coef - коэффициенты системы
%                    tol - точность fzero
%                    t - если между точками расстрояние меньше t, то точки
%                    совпадают
%
% Выходные данные: SS - структура, содержащая зависимость x(p)
%
% Внешние процедуры: Findingzeros, Newton,sorting
%
% Внутренние процедуры: Integr, ode45terminator,
% find_points_without_pair, termintor
%
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
syms p x
dfdp=diff(Y,p); %производная по параметру
dfdx(p,x)=diff(Y,x); %производная по переменной X
Ysyms = Y;
Y=matlabFunction(Y);
F=matlabFunction(-dfdp/dfdx);
%Когда интегрируем по времени при поиске стационарного состояния?(ответ:t-не время)
dt = 1.0e7; %шаг по параметру при вертикальном интегрировании
%
F_vertical=matlabFunction(-dfdx/dfdp);
dfdp(p,x) = dfdp;
nzf=zeros(1,size(par,2)); %массив из количества нулей на каждой нормали(любая прямая перпендикулярная изначальной прямой, на которой строилась сетка)
%Настройка аргументов для ode45
opt=odeset('Events',@(p,X) ode45terminator(X,p,dfdx),'AbsTol',1e-9,'RelTol',1e-9);
opt_vertical=odeset('Events',@(p,X) terminator(X,p,dfdp,lbfname,ubfname,coef),'AbsTol',1e-9,'RelTol',1e-9);
% а почему наз-ся нормалью?
Zeros=cell(2,size(par,2)); %структура, куда записываются нули на нормали
disp('Нахождение нулей');
for j=1:size(par,2)% шагаем по сетке
    %lbfname - имя процедуры, вычисляющей V_f_min при данном значении C_V,
    %//--//
    down = feval(lbfname,par(j),coef);
    up = feval(ubfname,par(j), coef);
    % down&&up - по V_f
    if(down <= up)
        f=Y(par(j),x);
        f=matlabFunction(f);
        [X,nz]=Findingzeros(down,up,tol,f);
        nzf(j)=nz;
        Zeros{1,j}=par(j);
        Zeros{2,j}=X';
    end
end
%
% % Отрисовка нулей функции без соединения
% for i=1:size(par,2)
%     if(size(Zeros{2,i},1)~=0)
%     figure(10)
%       plot(par(i),Zeros{2,i},'+k')
%       hold on
%     end
% end
%Нахождение номера узла по параметру, где меняется количество нулей
ioch=[];
for i=2:size(nzf,2)
    if nzf(i)~=nzf(i-1)
        a=[i;nzf(i)-nzf(i-1)];
        ioch=[ioch,a];
        fprintf(1,'В %g-ом узле по параметру количество нулей меняется на %g\n',a(1),a(2));
    end
end
disp('Соединение нулей');
% Найденные нули лежат как минимум на одной из заданных алгебраических кривых
Zeros{2,1}=sort(Zeros{2,1});%Сортируем нули при первом значении С_
kold=zeros(size((Zeros{2,1})'));
SS=cell(size(Zeros{2,1},2),2);% структура содержащая соединенные? стационарные состояния
for i=1:size(Zeros{2,1},1)
    SS{i,2}=Zeros{2,1}(i);
    SS{i,1}=Zeros{1,1};
    kold(i)=i;
end
counter = size(Zeros{2,1},1);
for j=2:size(par,2)
    %Точки остановок между двумя узлами
    break_points = cell(2,1);
    %Интегрирование из одного узла в другой
    for i=1:size(kold,2)
        [ss, break_point]=Integr(SS{kold(i),2}(end),[par(j-1),par(j)],dfdx,F,Ysyms,lbfname,ubfname, opt, coef);
        SS{kold(i),2}=[SS{kold(i),2},ss(2, 2:end)];
        SS{kold(i),1}=[SS{kold(i),1},ss(1, 2:end)];
        if size(break_point, 2) ~= 0
            break_points{1} = [break_points{1}, break_point];
            break_points{2} = [break_points{2}, kold(i)];
        end
    end
    %Ищем среди всех точек остановки точку без пары
    points_without_pair = find_points_without_pair(break_points, t);
    %Для всех точек остановки интегрируем по вертикали
    for i = 1:size(points_without_pair{1},2)
        %Определяем, вверх или вниз шла кривая до точки остановки находя
        %разнсть между значениями переменной x в точке остановки и
        %предыдущей точке
        dir = SS{points_without_pair{2}(i),2}(end) - ...
            SS{points_without_pair{2}(i),2}(end-1);
        %t0 и y0 - начальные точки интегрирования
        t0 = points_without_pair{1}(2, i);
        y0 = points_without_pair{1}(1, i);
        [tt, yy]= Integr_vertical(t0, y0, F_vertical, opt_vertical, dir, dt,lbfname, ubfname, coef);
        SS{points_without_pair{2}(i),2}=[SS{points_without_pair{2}(i),2},tt];
        SS{points_without_pair{2}(i),1}=[SS{points_without_pair{2}(i),1},yy];
    end
    %Уточнение с использованием структуры Zeros
    Xexp=[];
    knew=[];
    for i=1:size(kold,2)
        if (par(j)==SS{kold(i),1}(end))
            Xexp=[Xexp;SS{kold(i),2}(end)];
            knew=[knew,kold(i)];
        end
    end
    kold=knew;
    Xfinal=Zeros{2,j};
    if size(Xfinal,2) ~= 0
        Xfinal=(sorting(Xexp,Xfinal));
        for i=1:size(knew,2)
            SS{knew(i),2}(end)=Xfinal(i);
        end
    end
    if size(Zeros{2,j},1)>size(Xfinal,1)
        Xrest=[];
        for i=1:size(Zeros{2,j},1)
          if sum((Zeros{2,j}(i)==Xfinal))==0
              Xrest=[Xrest;Zeros{2,j}(i)];
          end
        end
        A=cell(size(Xrest,1),2);
        break_points = cell(2,1);
        SS=[SS;A];
            for i=1:size(Xrest,1)
                    SS{counter+i,2}=Xrest(i);
                    SS{counter+i,1}=Zeros{1,j};
                    [ss, break_point]=Integr(Xrest(i),[par(j),par(j-1)],dfdx,F,Ysyms,lbfname,ubfname,opt, coef);
                    SS{counter+i,2}=[ss(2,end:-1:2),SS{counter+i,2}];
                    SS{counter+i,1}=[ss(1,end:-1:2),SS{counter+i,1}];
                    kold=[kold,counter+i];
                    if size(break_point, 2) ~= 0
                        break_points{1} = [break_points{1}, break_point];
                        break_points{2} = [break_points{2}, counter+i];
                    end
            end
            counter = counter + size(Xrest,1);
            points_without_pair = find_points_without_pair(break_points, t);
            for i = 1:size(points_without_pair{1},2)
                dir = SS{points_without_pair{2}(i),2}(1) - ...
                    SS{points_without_pair{2}(i),2}(2);
                t0 = points_without_pair{1}(2, i);
                y0 = points_without_pair{1}(1, i);
                [tt, yy] = Integr_vertical(t0, y0, F_vertical, opt_vertical, dir, dt, lbfname, ubfname, coef);
                SS{points_without_pair{2}(i),2}=[tt(end:-1:1),SS{points_without_pair{2}(i),2}];
                SS{points_without_pair{2}(i),1}=[yy(end:-1:1), SS{points_without_pair{2}(i),1}];
            end
    end
end
end
function [ss,break_point]=Integr(xbeg,par,dYdx,F,Ysyms,lbfname,ubfname,opt,coef)
%Если интегрирование остановится, не дойдя до конца интервала par, то в
%break_point запишется точка остановки в виде [p; x]
break_point = [];
%Интегрирование останавливается только если dYdx(p_int,x_int) = 0, то есть, в точках
%"поворота"
[p_int,x_int]=ode45(F, par, xbeg, opt);
%Зачем уточнение методом НЬЮТОНА
%Если интегрирование не дошло до конца интервала par и при этом точка остановки
%лежит внутри рассматриваемой области, то уточняем её методом Ньютона
if p_int(end) ~= par(2) && x_int(end) >= feval(lbfname,p_int(end), coef) ...
        && x_int(end) <=  feval(ubfname,p_int(end), coef)
    syms p x
    %Вектор символьных переменных
    X = [p; x];
    %В точке "поворота" должна равняться нулю, как функция невязки Ysyms, так и
    %её производная dYdx (ведь это и было устовием остановки
    %интегрирования)
    Func = [formula(Ysyms); formula(dYdx)];
    [res] = Newton(X, Func, [p_int(end); x_int(end)], struct('tol',1e-9,'maxIter',10));
    p_int(end) = double(res(1));
    x_int(end) = double(res(2));
    break_point = [p_int(end); x_int(end)];
end
p_new = [];
x_new = [];
%Выкидываем из множества точек, полученного в ходе интегрирования все, что
%лежат за границей области, кроме самых ближайших к этой границе
%Записываем оставшиеся точки в массивы p_new, x_new, при этом разделяя
%разные фрагменты NaN кривых
for i = 1:size(p_int,1)
    %Проверяем, лежит ли точка внутри области
    if x_int(i) >= feval(lbfname,p_int(i), coef) ...
            && x_int(i) <= feval(ubfname,p_int(i), coef)
        %Если кривая вошла в область извне(в конце массива p_new лежит NaN)
        %то в новый массив стоит ещё добавить и предыдущую точку кривой, которая
        %лежит за границей
        if(size(p_new,2) ~= 0 && isnan(p_new(end)))
            p_new = [p_new, p_int(i-1)];
            x_new = [x_new, x_int(i-1)];
        end
        %Добавляем саму точку в массивы
        p_new = [p_new, p_int(i)];
        x_new = [x_new, x_int(i)];
    else
        %Если кривя только что вышла за границу(в конце массива p_new не лежит NaN)
        %то помещаем в конец p_new первую точку, которая окзалась вне
        %области, и NaN
        if ~isnan(p_new(end))
            p_new = [p_new, p_int(i), NaN];
            x_new = [x_new, x_int(i), NaN];
        end
    end
end
ss = [];
ss = [ss, p_new];
ss =[ss; x_new];
end
%Интегрирование по вертикали
function [t, y] = Integr_vertical(t0, y0, F_vertical, opt_vertical, dir, dt, lbfname, ubfname, coef)
        t = [];
        y = [];
        %Определяем знак dt, соответсвующий направление интегрирования(вверх - плюс,
        %вниз - минус ) в зависимости от того, как шла кривая до точки
        %остановки (знак dir).
        dt = sign(dir) * abs(dt);
        %Пока точка начала интегрирования t0 лежит внутри области, интегрируем
        %по вертикали от t0 до t0+dt
        while t0 > feval(lbfname, y0, coef) && t0 < feval(ubfname, y0, coef)
            [tt,yy]=ode45(F_vertical, [t0; t0+dt], y0, opt_vertical);
            t0 = t0 + dt;
            y0 = yy(end);
            t=[t,tt(2:end)'];
            y=[y,yy(2:end)'];
            %Если в ходе интегрирования выполнилось какое-либо терминальное
            %условие, то заканичваем цикл
            if tt(end) < t0
                break
            end
        end
end
%Поиск точек без пары среди точек остановки между двумя узлами сетки
function points_without_pair = find_points_without_pair(break_points, tol)
%tol - заданная точность, при которой считаем, что точки совпадают
    points_without_pair = cell(2, 1);
    %Проходим по всем точкам, кроме последней, из break_points
    for i = 1:size(break_points{1}, 2)-1
        %Проверяем, не равна ли данная точка NaN
        % Если в данной ячеке уже лежит NaN, то для лежавшей в ней точки
        %уже нашлась пара среди предыдущих точек
        if ~isnan(break_points{1}(1, i))
            isPaired = 0;
            %Проверяем для всех следующих точек, не является ли данная
            %их парой
            for k = i+1:size(break_points{1}, 2)
                if ~isnan(break_points{1}(1, i))
                    v = break_points{1}(:, i) - break_points{1}(:, k);
                    norm(v, 2);
                    %Просто проверяем расстояние между двумя точками
                    if norm(v, 2) < tol
                        isPaired = 1;
                        break_points{1}(:, k) = [NaN; NaN];
                        break;
                    end
                end
            end
            %Если пара не нашлась, добавляем точку в итоговый массив
            if ~isPaired
               points_without_pair{1} = [points_without_pair{1}, break_points{1}(:, i)];
               points_without_pair{2} = [points_without_pair{2}, break_points{2}(i)];
            end
        end
    end
    %Проверяем, поменялась ли последняя точка из break_points на NaN или
    %нет. Если нет, то для неё тоже не нашлось пары.
    if size(break_points{1}, 2) >= 1 && ~isnan(break_points{1}(1, end))
         points_without_pair{1} = [points_without_pair{1}, break_points{1}(:, end)];
         points_without_pair{2} = [points_without_pair{2}, break_points{2}(end)];
    end
end
function [value,isterminal,direction] = ode45terminator(X,p,dfdx)
    value=double(dfdx(p,X));
    isterminal=1;
    direction=0;
end
function [value,isterminal,direction] = terminator(X,p,dfdx,lbfname,ubfname,coef)
value=[double(dfdx(p,X));p-feval(lbfname,X,coef);p-feval(ubfname,X,coef)];
isterminal=[1;1;1];
direction=[0;0;0];
end